### PR TITLE
Put correct proxy

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Somehow some commits in sidecarProxy pull request have been lost during repository name changes and organization move.  This PR putting back code changes in the missing  commits.

### CODE REVIEW

**Comment by Tansito** [comment]
Ups, tell me If I can help you with this @akihikokuroda 🤦

**Comment by akihikokuroda** [comment]
I believe that I restored all changes.  I'm not sure how some commits got lost, though. :-(

**Review by Tansito — APPROVED** [review]
My two cents are that how we renamed folders something were wrong in that movement from one name to another 🤦 

LGTM, @akihikokuroda we can take a look more in-depth later

**Review by psschwei — APPROVED** [review]
I think it may have been in one of the rebases, but hard to tell for sure

**Pull request merged**
