### PR TITLE
Client get method

### PR DESCRIPTION
**Pull request by Tansito**
### Summary

As part of #1314 I implemented a `get` method only in the client as sugar syntax to get a Qiskit Function and avoid to iterate the list.

### CODE REVIEW

**Comment by Tansito** [comment]
@akihikokuroda , @IceKhan13 , @psschwei , what do you think? Do you prefer to maintain the `list` until finish the `get` or this could work as workaround in the meantime?

**Comment by akihikokuroda** [comment]
I don't have strong opinion but I prefer to maintain it for now.

**Comment by psschwei** [comment]
If the old functionality still works, I'd just wait for the new function to be completely ready rather than adding a workaround

**Comment by Tansito** [comment]
Ok, let's just leave as it is, then. Just in case we need to change the interface or something 👍

**Pull request closed without merging**
