### PR TITLE
Client: always cleanup artifact tar

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Fixes situation when something is happening during function upload and artifact tar remain in working directory

### CODE REVIEW

**Review by akihikokuroda — APPROVED** [review]
LGTM

**Review by Tansito — COMMENTED** [review]
One doubt @IceKhan13, with this approach we could raise the exception without remove the tar file, couldn't we? Are you maybe missing a `finally` statement? Like:

```py
try:
  # Logic here
except Exception as error:
  raise QiskitServerlessException from error
finally:
    if os.path.exists(artifact_file_path):
        os.remove(artifact_file_path)
```

(Take it as pseudo code, I don't know 100% if this example is correct in python 😂)

**Comment by IceKhan13** [comment]
you are absolutely right! haha! forgot to add `finally` What I was thinking?!

**Review by Tansito — APPROVED** [review]
Thank you, Iskandar!

**Pull request merged**
