### PR TITLE
Create scorecard.yml

### PR DESCRIPTION
**Pull request by akihikokuroda**
Add OSSF code scanning

### Summary
Add OSSF code scanning [scorecard](https://github.com/ossf/scorecard) in workflow

### Details and comments
I would like to try if this scan is useful.

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
+1 from me

**Comment by Tansito** [comment]
Interesting 🤔

**Comment by akihikokuroda** [comment]
I merge this.  Let's see how good it is 🤞

**Comment by Tansito** [comment]
Well, I was just reading the documentation and taking a look to the configuration. An approval it would be nice for the next time, Aki haha.

**Comment by akihikokuroda** [comment]
Sorry.

**Comment by Tansito** [comment]
Haha np, np. Just for the next time to give us some time to take a look (I didn't know the tool for example). One approval is fine but at least one from one of us 😄

**Pull request merged**
