### PR TITLE
chore(deps): bump pin on numpy requirement

### PR DESCRIPTION
**Pull request by robertodr**
### Summary
NumPy is only needed to run tests and examples. I've moved it to `requirements-dev.txt` as otherwise downstream packages cannot update to NumPy >=2.0.

### CODE REVIEW

**Review by paaragon — APPROVED** [review]

**Review by Tansito — COMMENTED** [review]
First of all thank you so much for your contribution @robertodr 

`client` is our library used in our `ray-node` image. Taking this into account `numpy` is a library very used in our entire stack so I don't think we can remove it so easily because it could be needed to run other functions that count with it.

My proposal would be to follow a similar requirement as [Qiskit](https://github.com/Qiskit/qiskit/blob/main/requirements.txt#L2):
```
numpy>=1.17,<3
```

So v2 would be supported.

**Comment by robertodr** [comment]
@Tansito I would be happy with lifting the version pinning as you suggest. However, keeping a package you don't directly depend on in your `install_requires`, just because other dependents _might_ need it, is, as far as I know, bad practice. The dependents should explicitly list that package in their `install_requires`.

**Comment by Tansito** [comment]
Well, our use case it's a bit special due to the usage that we are doing with our docker image. But thinking a bit more about it I think you are right here and it's better to move it to our -dev dependencies. Could you update your change with the same restriction as qiskit as we were discussing above?

Apart from that I think everything is fine 👍

**Comment by Tansito** [comment]
It seems there is an error in one of the tests @robertodr , I will take a look into it and let you know

**Comment by Tansito** [comment]
@robertodr from the tests it seems `numpy` is a required dependency, without it serverles is not able to run the functions. Could you apply the restriction in the `requirements.txt`?

We will take a look in the meantime what dependency requires to have `numpy` declared there, it's not clear. Thank you!

**Comment by Tansito** [comment]
sorry @robertodr it seems we continue with some incompatibilities, tomorrow I will take a look and let you know 🙏

**Comment by Tansito** [comment]
@robertodr I could finally identify the problem and we will take a look as soon as we can. I created this issue to keep you updated about the advances. I will close this PR in the meantime and open a new one as soon as we have it fix it!

**Comment by robertodr** [comment]
Ok thanks. Will subscribe to that issue

**Pull request closed without merging**
