### PR TITLE
validate uuid id/pk

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Validate UUID used as the id/pk for the model instance

### CODE REVIEW

**Review by Tansito — CHANGES_REQUESTED** [review]
Thanks for the PR, @akihikokuroda . You don't need to validate perse the UUID format. This is something that django is doing in its ORM. The problem is that we are not capturing the exception for that. The idea is to add a `try/except` in the queries where we are using the UUID.

**Comment by akihikokuroda** [comment]
These changes check the uuid before django validates it.  So it stops raising exceptions and returns 404 for the requests.

**Comment by Tansito** [comment]
> These changes check the uuid before django validates it. So it stops raising exceptions and returns 404 for the requests.

I know, I know. But we can rely on Django validation perfectly, we just need to capture the exception that it raises. We don't need to create our own validator for that.

**Comment by akihikokuroda** [comment]
I believe that the django validation happens when it saves to or retrieves from the database.  It's much cleaner and safer if we validate it at the entry of the apis.

**Comment by Tansito** [comment]
My proposal @akihikokuroda :
- We need to continue handling the exception in the queries anyway because we are not doing that right now. As the issue was proposing.
- I don't see bad to add additional checks but not through custom checks. We can use [UUID](https://docs.python.org/3/library/uuid.html) utility from python.
- Move the logic to utils and reuse it in those specific points.

**Comment by akihikokuroda** [comment]
> handling the exception in the queries

Are the **queries** database query? Where do you propose to put the `try` clause?

The UUID utility seems for generating an UUID.  I don't see the method for validating it.

**Comment by Tansito** [comment]
> Are the queries database query? Where do you propose to put the try clause?

It happens in every `find`, `filter`, etc that uses the `id` to search for something, example [here](https://github.com/Qiskit/qiskit-serverless/blob/main/gateway/api/views/catalog.py#L82).

You just need to encapsulate that call in a `try/except`, and in this case, return `None` is fine for example.

> The UUID utility seems for generating an UUID. I don't see the method for validating it.

If you try to create an UUID with a value that is not a valid UUID it will raise an exception that you can capture similar to what you were doing with the pattern.

**Comment by Tansito** [comment]
Let's close this PR by now and we can reschedule it in the next weekly

**Pull request closed without merging**
